### ISSUE TITLE
画的太棒了，请教个问题

### ISSUE THREAD

**Issue by superleeyom** [SmartKeyerror/Psyduck#1]
不得不说，画的实在太棒了，通俗易懂，简洁精炼，比较好奇，里面的这些数据结构，也都是借助 xmind 画出来了吗？还是说借助了其他的工具？
![image](https://user-images.githubusercontent.com/22115219/122325730-ae69a780-cf5d-11eb-9458-b0da401884ce.png)

**Comment by YianAndCode** [comment]
「图片是用 draw.io 做的，我把它们揉到了 XMind 里面」

详见： https://www.v2ex.com/t/783649#reply3

**Comment by superleeyom** [comment]
@YianAndCode cool
