### ISSUE TITLE
指令重排导致的读写问题主要发生在多线程的场景吧

### ISSUE THREAD

**Issue by xx1906** [SmartKeyerror/Psyduck#10]
https://github.com/SmartKeyerror/Psyduck/blob/master/go-concurrency/memory/memory_reordering_test.go 
// 这里的代码都是单线程执行的， 都会不管指令怎么重排都会 happen before 的吧

**Comment by SKeyerror** [comment]
是的，这里少了一个关键字，已修复

**Comment by xx1906** [comment]
我看看

**Comment by laxiaohong** [comment]
感觉这个好难模拟啊，获取用 c ++ 老版本的编译器编译会容易复现

**Comment by xx1906** [comment]
感觉这个好难模拟啊，或许用 c ++ 老版本的编译器编译会容易复现
