### ISSUE TITLE
想问一下画图用的是什么软件

### ISSUE THREAD

**Issue by kenxx** [SmartKeyerror/Psyduck#2]
如题

**Comment by SKeyerror** [comment]
图片是在 draw.io 这个在线绘图网站上做的，字体使用的是 Comic Sans MS。原图是在 MacOS 上绘制的，不过在 Ubuntu 和 Windows 操作系统下样式会有所差别。

**Comment by kenxx** [comment]
好的，我去试一下，谢谢
